# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
name: "Sreejith's Notes"
title: Sreejith's Notes
email: ssreejith@protonmail.com
description: ''
include: ["_pages"]
permalink: /:title/

# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  shortname: sreejithsnotes

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://srjit.github.io" # the base hostname & protocol for your site
twitter_username: srjit_
github_username:  srjit
paginate: 5
theme-dark: false #Set to true to change to dark website theme

plugins: [jekyll-paginate, kramdown]
# Build settings
markdown: kramdown

google_analytics: 'G-P56PDK6CCT'
